version: "3.5"
services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinhadb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"
    volumes:
      - rinha-db:/var/lib/postgresql/data

  api1: # API - Instância 01
    image: rinha-api:latest
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.0GB'

  api2: # API - Instância 02
    image: rinha-api:latest
    hostname: api2
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.0GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

volumes:
  rinha-db:

networks:
  default:
    driver: bridge